## holds quizzes

class Quiz:
    def __init__(self, question, answer, description):
        self.question = question
        self.answer = answer
        self.description = description

class smallQuiz:
    def __init__(self, q1, q2, q3, q4, q5, a1, a2, a3, a4, a5, headline, byline):
        self.questions = [q1, q2, q3, q4, q5]
        self.answers = [a1, a2, a3, a4, a5]
        self.headline = headline
        self.byline = byline

class footballQuiz:
    def __init__(self, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, headline, byline):
        self.questions = [p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11]
        self.answers = [a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11]
        self.headline = headline
        self.byline = byline 

class mediumQuiz:
    def __init__(self, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, headline, byline):
        self.questions = [p1, p2, p3, p4, p5, p6, p7, p8, p9, p10]
        self.answers = [a1, a2, a3, a4, a5, a6, a7, a8, a9, a10]
        self.headline = headline
        self.byline = byline 

class pictureQuiz:
    def __init__(self, url1, url2, url3, url4, url5, url6, a1, a2, a3, a4, a5, a6, headline, byline):
        self.questions = [url1, url2, url3, url4, url5, url6]
        self.answers = [a1, a2, a3, a4, a5, a6]
        self.headline = headline
        self.byline = byline

class flexQuiz:
    def __init__(self, *args, headline, byline):
        self.answers = args
        self.headline = headline
        self.byline = byline

## Geography quizzes

longestDeepest = smallQuiz("Deepest Loch?", "Longest Loch?", "Highest mountain in the Cairngorms?", "Longest River?", "Largest island?", "loch morar", "loch ness", "ben macdui", "tay", "lewis and harris", "Longest, Deepest, Highest", "Big Hitters, no subtlety here.")
rivers = smallQuiz("Longest river in Scotland", "Flowing through Aviemore, this river is known for salmon and whisky", "Flowing through Glasgow, this river was a shipbuilding hub for the British Empire", "97 miles long, this Borders river is closely linked to the cloth industry", "A short river at 29 miles, it is crossed by a rail bridge with UNESCO World Heritage Status", "tay", "spey", "clyde", "tweed", "forth", "Five Rivers", "All famous in their own way, can you guess the name of the river from it's description?")
castles = pictureQuiz("https://live.staticflickr.com/121/265309011_d309686251_b.jpg", "https://farm5.staticflickr.com/4206/35357323755_7f42d00379_b.jpg", "https://farm3.staticflickr.com/2525/4048504901_1ca87dbe0a.jpg", "https://live.staticflickr.com/3565/3819489715_d906ab48e9_b.jpg", "https://live.staticflickr.com/7639/26934734045_8f4894fa55_b.jpg", "https://live.staticflickr.com/2904/33282255844_4318388014_b.jpg", "dunnottar", "edinburgh", "urquhart", "eilean donan", "stirling", "inverness", "Castles", "Can you guess the castle?")
munroPicture = pictureQuiz("https://live.staticflickr.com/358/31136811684_72080fc49f_b.jpg", "https://upload.wikimedia.org/wikipedia/commons/b/b5/Sgurr_nan_Gillean_-_panoramio.jpg", "https://live.staticflickr.com/3024/2631449197_88e12f40bf_b.jpg", "https://s0.geograph.org.uk/geophotos/01/34/54/1345429_4ad1d245.jpg", "https://live.staticflickr.com/8675/15473307583_275b620d8a_b.jpg", "http://s0.geograph.org.uk/geophotos/02/78/21/2782102_190b9f41.jpg", "ben nevis", "sgurr nan gillean", "sgurr alasdair", "carn mor dearg", "buachaille etive more", "ben wyvis", "Munros: Picture round", "Some easy, some more difficult, how many of these munros can you guess?")
nameTheLoch = smallQuiz("Loch with greatest surface area?", "Loch with greatest volume of water", "Longest loch?", "Loch with greatest mean depth?", "Deepest loch?", "loch lomond", "loch ness", "loch awe", "loch ness", "loch morar", "Name the loch", "Only one loch appears twice.")
snowiestPlaces = smallQuiz("A popular ski resort, this weather station if officially the snowiest place in the UK", "This snowy Highland town became a railway junction in 1898", "These northerly isles see around 65 snow days a year", "Best known for knitwear, this tiny isle gets plenty of snow", "The second highest village in Scotland, it has a rich mining history", "cairngorm", "aviemore", "shetland", "fair isle", "leadhills", "Snowiest Places", "Can you name five of the most snowiest places in Scotland?")
geoBridges = pictureQuiz("https://live.staticflickr.com/7777/17460525479_1ecc40f009_b.jpg", "https://farm1.staticflickr.com/360/31941208555_075c11283f_b.jpg", "https://live.staticflickr.com/8314/7955436314_2faa5fb930_b.jpg", "https://live.staticflickr.com/119/300190786_70ee6f1366.jpg", "https://farm4.staticflickr.com/3148/2477762111_5de7317a5f_b.jpg", "https://live.staticflickr.com/3513/4009073734_0007d5ed6f_b.jpg", "forth railway bridge", "tay railway bridge", "kylesku bridge", "kessock bridge", "skye bridge", "carrbridge", "Iconic Bridges", "Can you name these six iconic Scottish bridges?")
scottishGlens = pictureQuiz("https://farm8.staticflickr.com/7426/13089694775_84e597a59d_b.jpg", "https://live.staticflickr.com/5788/22476010531_b85e0eed3e_b.jpg", "https://api.creativecommons.engineering/t/http://s0.geograph.org.uk/geophotos/05/46/60/5466074_dfebbc73.jpg", "https://live.staticflickr.com/7327/27181561820_3a6fe7f26d_b.jpg", "https://live.staticflickr.com/1533/25461838163_5a76875e25_b.jpg", "https://live.staticflickr.com/3104/3158859559_bcf15db135_b.jpg", "glencoe", "glen etive", "glen feshie", "glen lyon", "glen trool", "great glen", "Great Glens", "There's hundreds of them, but can you guess these six?")
pictureRivers = pictureQuiz("https://live.staticflickr.com/945/40277532420_52090c9353_b.jpg", "https://live.staticflickr.com/7450/16199696229_7c354e2c0d_b.jpg", "https://farm8.staticflickr.com/7313/10409310925_826abfaff0_b.jpg", "https://farm4.staticflickr.com/3874/14979521522_1c72eb307e_b.jpg", "https://live.staticflickr.com/1747/40905744550_fd5b2550e8_b.jpg", "https://live.staticflickr.com/65535/49263146631_9884e74d02_b.jpg", "tay", "spey", "tweed", "clyde", "forth", "nith", "Scottish Rivers", "Can you guess these beuatiful Scottish rivers?")
wettestTowns = flexQuiz("greenock", "glasgow", "paisley", "ivingston", "bonnyrigg", "dumfries", "stirling", "grangemouth", "inverness", "aberdeen", headline="Wettest Places", byline="Can you name Scotland's wettest towns/cities?")
sunniestPlaces = flexQuiz("st andrews", "arbroath", "kilmarnock", "aberdeen", "edinburgh", "dundee", "perth", "greenock", "dumfries", "livingston", headline="Sunniest Towns/Cities", byline="Can you guess some of Scotland's sunniest towns and cities?")
beaches = pictureQuiz("https://live.staticflickr.com/65535/49589820032_50522fc19f_b.jpg", "https://s0.geograph.org.uk/geophotos/02/58/97/2589766_aec6ed28.jpg", "https://live.staticflickr.com/4060/4416876704_a76bda5450_b.jpg", "https://farm5.staticflickr.com/4256/34752567124_7b45c1bcf6_b.jpg", "https://api.creativecommons.engineering/t/http://s0.geograph.org.uk/geophotos/02/59/28/2592824_ac22de8c.jpg", "https://api.creativecommons.engineering/t/http://s0.geograph.org.uk/photos/15/53/155375_5130d014.jpg", "luskentyre", "st ninians isle", "tolsta", "aberdeen", "west sands", "achmelvich", "Scottish Beaches", "Can you name these awesome stretches of sand?")
nameTheCity = pictureQuiz("https://live.staticflickr.com/7880/39834296313_032f5f7746_b.jpg", "https://live.staticflickr.com/65535/48931704556_a755768a75_b.jpg", "https://live.staticflickr.com/7326/27390281131_db1a0776f5_b.jpg", "https://live.staticflickr.com/7283/8737178791_61b7f61cb1_b.jpg", "https://live.staticflickr.com/5587/15298168115_821796d78a_b.jpg", "https://live.staticflickr.com/119/300190786_70ee6f1366.jpg", "edinburgh", "glasgow", "aberdeen", "dundee", "stirling", "inverness", "Scottish Cities", "Difficulty level: easy")

## People Quizzes
famousScots = mediumQuiz("Author, died in Abbotsford, Roxburghshire in 1832", "Economist, wrote An Inquiry into the Nature and Causes of the Wealth of Nations", "King of Scotland between 1306 and 1329", "Lead singer of Primal Scream", "First name of J. K. Rowling", "Author of Treasure Island", "In 1995 he became the youngest person to win the World Rally Championship Drivers' title", "Golfer, born 1963, he won seven consecutive European Tour Order of Merit Titles", "Twelfth incarnation of the Doctor in Doctor Who", "Inaugural First Minister of Scotland", "walter scott", "adam smith", "robert the bruce", "bobby gillespie", "joanne", "robert louis stevenson", "colin mcrae", "colin montgomerie", "peter capaldi", "donald dewar", "Scottish Top Ten", "You've probably heard of most of them.")
politicians = smallQuiz("First Minister of Scotland between 2007 and 2014", "British Prime Minister 2007-2010", "Inaugural First Minister of Scotland", "Leader of the Scottish Conservative Party 2011-2019", "Served as First Minister between 2001 and 2007", "alex salmond", "gordon brown", "donald dewar", "ruth davidson", "jack mcconnell", "Scottish Politicians", "You need to know your post-devolution Scottish history here.")
fiveActors = smallQuiz("Born in 1979 he has starred in Atonement, the Last King of Scotland and X-Men", "Born in 1971 you will know him from the young Obi-Wan Kenobi in Star Wars: Episode I or Mark Renton in Trainspotting", "Seven Bond Films, need I say more?", "From Broadchurch and Doctor Who to RSC's Hamlet, this man can do it all", "You should only need to know he starred in Trainspotting, The Full Monty and The World is not Enough", "james mcavoy", "ewan mcgregor", "sean connery", "david tennant", "robert carlyle", "Five Actors", "Given the description, can you name the actor?")

## Mountain quizzes

skiAreaHeights = smallQuiz("1,230m", "1,221m", "1,070m", "900m", "775m", "cairngorm", "nevis range", "glencoe", "glenshee", "the lecht", "Ski Areas, by height", "Unlikely to have any snow at all by 2080, enjoy them while you can.")
fiveHighest = smallQuiz("1,345m", "1,309m", "1,296m", "1,291m", "1,234m", "ben nevis", "ben macdui", "braeriach", "cairn toul", "aonach beag", "Mountains: five highest", "Hint: there's only two Bens in there")
tenHighest = mediumQuiz("1,345m", "1,309m", "1,296m", "1,291m", "1,234m", "1,223m", "1,214m", "1,196m", "1,183m", "1,182m", "ben nevis", "ben macdui", "braeriach", "cairn toul", "aonach beag", "caen mor dearg", "ben lawers", "beinn a bhuird", "carn eige", "beinn mheadhoin", "Ten Highest Mountains", "Given the heights, can you name the ten highest Scottish mountains?")
skiAreaPictures = pictureQuiz("https://s0.geograph.org.uk/geophotos/05/46/21/5462100_ebd17818.jpg", "https://farm6.staticflickr.com/5492/11953233084_0f38f592bb_b.jpg", "https://live.staticflickr.com/1120/577157476_f4588f3de7_b.jpg", "https://live.staticflickr.com/65535/32899809127_c0b9ea56b0_b.jpg", "https://live.staticflickr.com/2306/2246674786_b5ebaf49f9_b.jpg", "https://upload.wikimedia.org/wikipedia/commons/2/2d/Ski_tow_lift_on_Lowther_Hill_-_panoramio.jpg", "the lecht", "glencoe", "nevis range", "cairngorm", "glenshee", "lowther hills", "Ski areas", "Difficult, unless you're an avid Scottish Skier perhaps")
nonMunros = smallQuiz("731m, an iconic mountain close to Lochinver", "438 metres, translated as the pinnacle of the pool river", "One the best known summits in Scotland, this mountain has three summits with the middle one being particularly difficult to ascend", "Non-mainland corbett with the greatest prominence", "A 2007 survey confirmed this far north-west Corbett to be 3.7 metres short of a Munro", "suilven", "stac pollaidh", "the cobbler", "goat fell", "foinaven", "Non-munros", "Challenging, can you name these non-munros?")
fiveInGlencoe = smallQuiz("At the head of Glen Etive, this pyramid-shaped mountain is an icon", "A 742m peak guarding the entrance to Glencoe", "The central summit of the Aonach Eagach ridge", "The western summit of Aonach Eagach", "A subsidiary peak of Bidean nam Bian, it was reclassified in 1997 as a munro", "buachille etive mor", "pap of glencoe", "meall dearg", "sgorr nan fiannaidh", "stob coire sgreamhach", "Gencoe Five", "Knowing them is one thing, spelling them quite another.")
compassMunros = Quiz("Which is the most Easterly Munro?", "mount keen", "Compass Point Munros")

## Island Quizzes

islandCapitals = smallQuiz("Orkney", "Skye", "Bute", "Arran", "Barra", "kirkwall", "portree", "rothesay", "lamlash", "castlebay", "Island capitals/main towns", "Forget Edinburgh, can you name some of Scotland's principal Island towns?")
tenIslands = mediumQuiz("Home to the Cuillin Hills", "Known for its brightly coloured town Tobermory", "Scotland in miniature, this island is separated from the Hebrides by the Mull of Kintyre", "Nine distilleries call this island home", "Its abbey was founded by Columba in 563", "The Paps of ?", "Contains some of the oldest and best-preserved Neolithic sites in Europe", "A subartic archipelago lying 80km northeast of Orkney", "Home to Kinloch Castle", "Halfway between Orkney and Shetland", "skye", "mull", "arran", "islay", "iona", "jura", "orkney", "shetland", "rum", "fair isle", "Ten Islands", "Scotland has 94 permanently inhabited islands, can you name ten?")
largestIslands = Quiz("What is the largest island in Scotland?", "lewis and harris", "Largest Islands")


## History Quizzes

battles = smallQuiz("1314", "1745", "1297", "1513", "1307", "bannockburn", "culloden", "stirling bridge", "flodden", "loudon hill", "Battles by date", "Given a date, can you guess some of the major battles in Scotland's history?")
historyTopTen = mediumQuiz("Who is the current Lord of the Isles?", "In which year was the Union with Scotland Act signed?", "In which year was the Declaration of Arbroath signed?", "In which year did the SNP gain their first seat in Westminister?", "What is the largest Roman construction within Scotland?", "In which year was Balmoral Estate purchased by Queen Victoria?", "In which year did the new Scottish Parliament Building open?", "Located on the Bay of Skaill, which neolithic settlement consists of eight clustered houses?", "Since which year has Nicola Sturgeon served as First Minister of Scotland?", "In which year was Orkney absorbed into the Kingdom of Scotland?", "prince charles", "1706", "1320", "1945", "antonine wall", "1848", "2004", "skara brae", "2014", "1472", "Historical Top Ten", "Neolithic to now.")
orkney5 = smallQuiz("Large chambered cairn and passage grave, dating from around 3000BC", "Henge and stone circle 104 metres in diameter", "Five remaining megaliths of a henge", "Isbister Chambered Cairn, or tomb of the ?", "Stone built Neolthic settlement, located on the Bay of Skaill", "maeshowe", "ring of brodgar", "stones of stenness", "eagles", "skara brae", "Neolthic Orkney - top 5", "Can you name the neolithic monument from the description?")

## Music Quizzes

bandByAlbum = smallQuiz("Songs for Polarbears", "Sonic Flower Groove", "This is the Story", "Captain", "Blackened Sky", "snow patrol", "primal scream", "the proclaimers", "idlewild", "biffy clyro", "Bands by (first) Album", "Given the first album, can you guess the band?")
nameTheBand = smallQuiz("Final Straw was their breakthrough", "Post-rock band typically composing lengthy guitar-based instrumental pieces", "Scremadelica", "Belle and ?", "They share their name with an American state", "snow patrol", "mogwai", "primal scream", "sebastian", "texas", "Five Bands", "Five questions, five bands, can you name them?")

## Cities Quizzes
cityOrNot = smallQuiz("Perth", "Paisley", "Stirling", "Hamilton", "Cumbernauld", "yes", "no", "yes", "no", "no", "City or not?", "Are these cities? Yes/No")
guessTheCity = smallQuiz("Home to the Royal Mile", "Home to Rangers and Celtic", "The oil city", "A new V&A museum opened up here in 2018", "Commonly known as the capital of the Highlands", "edinburgh", "glasgow", "aberdeen", "dundee", "inverness", "Guess the city", "Given a description, can you guess the city?")

## Sport Quizzes

scotland1978XI = footballQuiz("1", "4", "13", "14", "22", "6", "7", "10", "11", "8", "9", "alan rough", "martin buchan", "stuart kennedy", "tom forsyth", "kenny burns", "bruce rioch", "don masson", "asa hartford", "willie johnston", "kenny dalglish", "joe jordan", "Scotland 1978", "Starting XI by squad number.")
spflGroundSize = mediumQuiz("60,832", "51,082", "22,199", "20,420", "20,099", "18,128","14,209", "13,742", "12,175", "12,085", "celtic park", "ibrox", "pittodrie", "easter road", "tynecastle park", "rugby park", "tannadice", "fir park", "somerset park", "dens park", "Scottish Football, grounds by capacity", "The first two shouldn't pose any problems.")
scottishCyclists = smallQuiz("Track cyclist, eleven times world champion, six-times Olympic champion", "First Brit to win a major Tour de France classification", "Road cyclist, rode for Cofidis 1997-2004 and Garmin 2008-2014", "Scottish trials cyclist from Dunvegan, Skye, uploaded his first stunt video to Youtube in 2009", "Broke the world hour record twice, also known for his homemade Old Faithful bicycle", "chris hoy", "robert millar", "david millar", "danny macaskill", "graeme obree", "Scottish Cyclists", "Road, track and mtb all represented here.")

## Highland Quizzes

railwayStations = pictureQuiz("https://live.staticflickr.com/65535/48935208796_d07e09a69b_b.jpg", "https://live.staticflickr.com/8368/8397570639_42b634c116_b.jpg", "https://upload.wikimedia.org/wikipedia/commons/c/c7/Corrour_Station_House%2C_Corrour_Station_-_geograph.org.uk_-_111650.jpg", "https://s0.geograph.org.uk/geophotos/04/55/99/4559940_e735cfff.jpg", "https://live.staticflickr.com/6035/6282724673_0d7a95ff32_b.jpg", "https://live.staticflickr.com/4042/4234707885_a56ffb673b_b.jpg", "aviemore", "kyle of lochalsh", "corrour", "mallaig", "glasgow central", "rannoch moor", "Name the station", "Beautiful stations, but can you guess where they are?")
ferryPorts = smallQuiz("Stornoway", "Stromness", "Craignure", "Dunoon", "Brodick", "ullapool", "scrabster", "oban", "gourock", "ardorssan", "Ferry Ports", "Where would you take the ferry from to reach these places?")
ferryPorts2 = pictureQuiz("https://farm4.staticflickr.com/3193/2653799086_9d04939301_b.jpg", "https://farm3.staticflickr.com/2718/4240848369_bddc538032_b.jpg", "https://live.staticflickr.com/3140/2706734446_5aa5f67a92_b.jpg", "https://farm5.staticflickr.com/4044/4497808608_d87f847a98_b.jpg", "https://s0.geograph.org.uk/geophotos/05/47/05/5470538_84e175f1.jpg", "https://live.staticflickr.com/5585/14268548404_e4db1e0898_b.jpg", "mallaig", "ullapool", "aberdeen", "lerwick", "corran", "uig", "Ferry Ports", "Can you name the town from the port?")
highlandTowns = pictureQuiz("https://farm4.staticflickr.com/3848/14895647012_3d2c62580f_b.jpg", "https://s0.geograph.org.uk/geophotos/06/09/99/6099929_85f598b5.jpg", "https://s0.geograph.org.uk/geophotos/04/47/58/4475821_b7da1701.jpg", "https://live.staticflickr.com/3210/2986982623_3e458d7e3a_b.jpg", "https://upload.wikimedia.org/wikipedia/commons/6/68/Arrochar_-_panoramio.jpg", "https://farm4.staticflickr.com/3903/15164576078_c67674947c_b.jpg", "stirling", "cromarty", "tomintoul", "portree", "arrochar", "stromness", "Highland Towns", "Some big, some little, can you guess these highland towns?")
hebrideanIslands = pictureQuiz("https://live.staticflickr.com/8314/29792851705_c170388d5b_b.jpg", "https://live.staticflickr.com/65535/48317320661_c5603ee385_b.jpg", "https://live.staticflickr.com/65535/47936740137_31af1a55f7_b.jpg", "https://api.creativecommons.engineering/t/http://s0.geograph.org.uk/geophotos/03/69/27/3692704_dce1fd8b.jpg", "https://live.staticflickr.com/13/18340398_dab80f6fb2.jpg", "https://api.creativecommons.engineering/t/http://s0.geograph.org.uk/geophotos/02/96/81/2968125_6ae2debd.jpg", "barra", "eriskay", "benbecula", "harris", "lewis", "vatersay", "Hebridean Islands", "Can you name these beautiful Hebridean islands?")
famousLochs = pictureQuiz("https://live.staticflickr.com/46/171490896_741b835f8d.jpg", "https://upload.wikimedia.org/wikipedia/commons/6/63/The_Glenfinnan_Monument_from_Loch_Shiel_%28geograph_4367802%29.jpg", "https://live.staticflickr.com/6132/5944576104_8d292b8687_b.jpg", "https://live.staticflickr.com/2894/33508369813_a02065dbc5_b.jpg", "http://s0.geograph.org.uk/geophotos/05/47/05/5470523_586ef01a.jpg", "https://farm3.staticflickr.com/2298/2085182448_e16cf6cb18_b.jpg", "loch ness", 'loch shiel', "loch lomond", "loch katrine", "loch linnhe", "loch tay", "Famous lochs", "Can you name these famous Highland lochs?")
highlandMunros = pictureQuiz("https://farm1.staticflickr.com/358/31136811684_72080fc49f_b.jpg", "https://s0.geograph.org.uk/geophotos/02/75/86/2758628_5629e488.jpg", "https://live.staticflickr.com/1536/25539356373_307e4c890d_b.jpg", "https://live.staticflickr.com/1430/544434747_2671a2ad5b_b.jpg", "https://live.staticflickr.com/755/22278220209_2848975f7c_b.jpg", "https://live.staticflickr.com/4176/34486933472_d566d0b363_b.jpg", "ben nevis", "ben more assynt", "liathach", "an teallach", "buachaille etive mor", "schiehallion", "Highland Munros", "Challenging to climb and to spell, can you name these famous highland Munros?")
highlandHistory = pictureQuiz("https://live.staticflickr.com/5778/29966805751_e65e13338c_b.jpg", "https://live.staticflickr.com/10/17381702_31adeed51d.jpg", "https://live.staticflickr.com/4206/35357323755_7f42d00379_b.jpg", "https://live.staticflickr.com/4101/4856865265_c1d9b44ed2_b.jpg", "https://live.staticflickr.com/668/22666736990_f531f59706_b.jpg", "https://farm6.staticflickr.com/5595/14709368417_244229d9bb_b.jpg", "wallace monument", "skara brae", "edinburgh castle", "eilean donan castle", "callanish", "glenfinnan viaduct", "Highland History", "Neolithic to nineteenth century, how many historical places can you name?")
hebrideanIsles = pictureQuiz("https://live.staticflickr.com/65535/49421661146_5c3ee6f01e_b.jpg", "https://live.staticflickr.com/2539/3935311702_aef6c7ff69_b.jpg", "https://live.staticflickr.com/16/23013976_a6b94aa87b.jpg", "https://farm9.staticflickr.com/8153/29679987522_a12fa62d88_b.jpg", "https://farm5.staticflickr.com/4037/4348866304_f2cc60be47_b.jpg", "https://live.staticflickr.com/7877/39978038233_2bf0147a12_b.jpg", "skye", "mull", "staffa", "barra", "eigg", "jura", "Hebridean Islands", "Easy if you've frequented the West Coast.")
quickFiveHighlandHistory = smallQuiz("Battle of ? saw Scotland defeat England in 1314", "Battle of ? was the final battle in the 1745 Jacobite rising", "? castle lies at the top of the Royal Mile", "Vallum Antonini or ? Wall was a Roman wall built in the Scottish central belt", "Skara ? is a stone-built Neolithic settlement", "bannockburn", "culloden", "edinburgh", "antonine", 'brae', "Highland History Quick Five", "Can you fill in the blanks of these key historical moments?")
historicHighlandCounties = smallQuiz("Bounded only by Sutherland and the sea", "A county town of Dornoch and some of the most dramatic scenery in Europe", "Touching east and west Scotland, this county borders Invernesshire to the south and Sutherland to the north", "Fomerly Dal Riata, this county contains a large number of the Inner Hebrides", "Drumochter to Rannoch Moor, Ben Lui to Aberfoyle", "caithness", "sutherland", "ross and cromarty", "argyll", "perthshire", "Historic Highland Counties", "Although formally replaced by the Highland Council, these names are well known")
highlandBreweries = smallQuiz("Northernmost in the UK", "Isle brewery, not on an Island?", "Brewery address: The Pier, Uig", "Neslted in Aviemore", "Brewing mammoth headquartered in Ellon, Aberdeenshire", "valhalla", "black isle", "isle of skye", "cairngorm", "brewdog", "Scottish Breweries", "Scotland has more than 100 craft breweries, can you guess five?")
highlandDistilleries = smallQuiz("Best-selling Islay Whisky", "The only distillery on Skye", "A Cairngorm distillery located near Tomintoul", "The world's best-selling single-malt whisky, it's name translates as valley of the deer", "The smallest distillery in Scotland?", "laphroaig", "talisker", "glenlivet", "glenfiddich", "edradour", "Scottish Distilleries", "Scotland's most famous export, can you name five famous distilleries?")
highlandRivers = smallQuiz("The longest river in Scotland", "A long Cairngorm river feeding many distilleries", "This famous salmon-fishing river passes through the Balmoral estate", "A river that both flows through Aberdeen and gives the football team their name", "A long highland river that rises in the Monadhliath mountains and flows into the Moray firth", "tay", "spey", "dee", "don", "findhorn", "Highland Rivers", "Four easy, one harder, can you get all five?")
highlandMountainPasses = smallQuiz("A winding single track road through the Applecross peninsula", "The main mountain pass between northern and southern central Highlands through which the A9 and railway pass", "The second highest place on the Inverness-Perth A9", "The border between Perthshire and Aberdeenshire crosses this road, the highest main road in the UK", "This road unites Cock Bridge and Tomintoul", "bealach na ba", "drumochter", "slochd", "cairnwell", "the lecht", "Mountain Passes", "Can you name these famous Scottish mountain passes?")
## highlandMountainPasses2 = pictureQuiz()
## highlandBeaches = pictureQuiz()
## highlandCastles = pictureQuiz()
## railwayStations2 = pictureQuiz()
## highlandIslands = mediumQuiz()
highlandPeninsulas = mediumQuiz("The most westerly point of mainland Britain is found here", "Called an Isle, it contains the towns Fortrose and Cromarty", "Paul McCartney lived here", "northernmost peninsula on Skye", "Peninsula that encompasses Dunoon and the Arrochar Alps", "Often referred to as Britain's last wilderness, it is not connected to Britain's road network", "Peninsula known as the garden of Skye", "Bhatairnis in Gaelic", "Its name means Deer Headland in Gaelic, it lies between Loch Dunvegan and Loch Bracadale", "The Rhins of ?", "ardnamurchan", "black isle", "mull of kintyre", "trotternish", "cowal", "knoydart", "sleat", "waternish", "duirinish", "galloway", "Scottish Peninsulas", "You could spend a lifetime visiting these beautiful places")
highlandRailwayStations = mediumQuiz("Heading south from Altnabreac", "The stop between Duncraig and Duirinish", "Heading south, the stop after Aviemore", "Nairn, Forres and then?", "Heading south from Mallaig", "Roy Bridge, Spean Bridge and then?", "Between Helensburgh Upper and Arrochar and Tarbet", "Highest mainline station in the UK","Smallest and most northerly settlement in the UK to be served by more than one railway station", "Originally a private railway staton, it now opens when the castle it provides access to is also open", "forsinard", "plockton", "kingussie", "elgin", "morar", "fort william", "garelochhead", "corrour", "tyndrum", "dunrobin castle", "Highland Railway Stations", "Can you guess the station from the description?")
highlandFalls = mediumQuiz("An 113m drop which requires an 8k hike to see", "Scotland's second highest waterfall with a drop of 120m", "A waterfall of 165 feet that feeds loch ness", "A series of falls 8 miles from Pitlochry", "A tidal race that forms at the mouth of Loch Etive", "Located on the river Cassley in Sutherland", "A cascade of waterfalls located at Killin", "Literally meaning waterfall waterfall, this waterfall is found on Mull", "A waterfall found between Loch Leathan and Bearreraig Bay", "Linn of ?, near Ballter, Upper Deeside", "falls of glomach", "steall waterfall", "falls of foyers", "falls of bruar", "falls of lora", "achness falls", "falls of dochart", "eas fors", "bearreraig", "quoich", "Highland Waterfalls", "Challenging to name, challenging to spell, can you get all ten waterfalls?")

## Jumbo Quizzes

inhabitedIslands = flexQuiz("lewis and harris", "mainland shetland", "mainland orkney", "skye", "bute", "arran", "islay", "mull", "south uist", "great cumbrae", "north uist", "benbecula", "barra", "whalsay", "yell", "south ronaldsay", "tiree", "west burra", "unst", "westray", "seil", "sanday", "bressay", "burray", "stronsay", "scalpay", "shapinsay", "hoy", "great bernera", "luing", headline="Most Populated Islands", byline="Can you name the top 30 inhabited Scottish Islands?")
jumboTowns = flexQuiz("glasgow", "edinburgh", "aberdeen", "dundee", "paisley", "east kilbride", "livingston", "hamilton", "dunfermline", "cumbernauld", "kirkcaldy", "perth", "inverness", "ayr", "kilmarnock", "coatbridge", "greenock", "glenrothes", "stirling", "airdrie", "falkirk", "irvine", "dumfries", "motherwell", "rutherglen", "wilshaw", "cambuslang", "bearsden", "newton mearns", "clydebank", headline="Most Populated Towns", byline="Can you name the top 30 populated towns in Scotland?")
jumboMunros = flexQuiz("ben nevis", "ben macdui", "braeriach", "cairn toul", "sgor an lochain uaine", "cairn gorm", "aonach beag", "aonach mor", "carn mor dearg", "beinn a' bhuird", "beinn mheadhoin", "carn eige", "mam sodhail", "stob choire claurigh", "ben more", "ben avon", "stob binnein", "beinn bhrotain", "lochnagar", "derry cairngorm", "sgurr nan ceathreamhnan", "sgurr na lapaich", "bidean nam bian", "ben alder", "geal-charn", "ben lui", "binnein mor", "an riabhachan", "creag meagaidh", headline="Highest Munros", byline="Serious Munro Baggers only")
jumboScottishConstituencies = flexQuiz("linithgow", "edinburgh central", "edinburgh northern and leith", "glasgow kelvin", "inverness and nairn", "edinburgh eastern", "almond valley", "midloathian north and musselburgh", "edinburgh western", "aberdeen central", "kilmarnock and irvine valley", "edinburgh southern", "glasgow pollock", "aberdeenshire east", "falkirk east", "moray", "aberdeen donside", "strathkelvin and bearsden", "glasgow shettleston", "falkirk west", "aberdeen south and north kincardine", "east lothian", "midlothian south, tweeddale and lauderdale", "perthshire south and kinross-shire", "kirkcaldy", "dundee city west", "edinburgh pentlands", "rutherglen", "east kilbride", "dunfermline", headline="Scottish UK Parliamentary Constituencies", byline="Can you guess the 30 largest by population?")
jumboCorbetts = flexQuiz("beinn a chlaidheimh", "beinn dearg", "sgurr nan ceannaichean", "sgurr a choire-bheithe", "beinn bhreac", "leathad an taobhain", "the fara", "foinaven", "beinn nan oighreag", "streap", "meall biudhe", "beinn maol chaluim", "fuar tholl", "leum uilleim", "beinn dearg mor", "ben tee", "beinn damh", "ben vuirich", "beinn an lochain", "beinn odhar", "sguur an fhuarain", "beinn mheadhonach", "culardoch", "aonach buidhe", "sgurr nan eugallt", "beinn a bhuiridh", "ben tirran", "gairbeinn", "ruadh-stac beag", "beinn bhan", headline="Highest Corbetts", byline="Can you name the top 30 Corbetts?")

## General Knowledge Quizzess

generalKnowledge = smallQuiz("Capital city?", "Highest mountain?", "Largest city?", "Oldest university?", "Longest river?", "edinburgh", "ben nevis", "glasgow", "st andrews", "tay", "General Knowledge", "Quick, simple general knowledge quiz.")
gaelicPlaceNames = mediumQuiz("Inbhir Nis", "Dun Eideann", "Glaschu", "An Gearasdan", "Port Righ", "An t-Eilean Sgitheanach", "Ulapul", "Cromba", "Beinn Nibheis", "An t-Archar", "inverness", "edinburgh", "glasgow", "fort william", "portree", "isle of skye", "ullapol", "cromarty", "ben nevis", "arrochar", "Gaelic Placenames", "Given the Gaelic, can you guess the English?")
shires = flexQuiz("caithness", "sutherland", "ross-shire", "cromartyshire", "inverness-shire", "nairnshire", "elginshire", "banffshire", "aberdeenshire", "kincardineshire", "forfarshire", "perthshire", "argyll", "bute", "ayrshire", "renfrewshire", "dumbartonshire", "stirlingshire", "clackmannanshire", "kinross-shire", "fife", "linlithgowshire", "edinburghshire", "haddingtonshire", "berwickshire", "roxburghshire", "dumfriesshire", "kirkcudbrightshire", "wigtownshire", "lanarkshire", "selkirkshire", "peebleshire", headline="Scottish Historic Shires", byline="Can you name all 32 historic shires?")
councils = flexQuiz("city of glasgow", "city of edinburgh", "fife", "north lanarkshire", "south lanarkshire", "aberdeenshire", "highland", "city of aberdeen", "west lothian", "renfrewshire", "falkirk", "perth and kinross", "dumfries and galloway", "city of dundee", "north ayrshire", "east ayrshire", "angus", "scottish borders", "south ayrshire", "east dunbartonshire", 'east lothian', "moray", "east renfrewshire", "stirling", "midlothian", "west dumbartonshire", "argyll and bute", "inverclyde", "clackmannanshire", "western isles", "shetland islands", "orkney islands", headline="Scottish Councils", byline="Can you name all 32 Scottish Council Areas?")